### ISSUE TITLE
Disuse SETNX

### ISSUE THREAD

**Issue by espadrine** [qonto/idempotent-request#2]
We currently rely on SETNX [here](https://github.com/qonto/idempotent-request/blob/ba8240b54dd31edb681d805eecd5da51c30e5f0f/lib/idempotent-request/redis_storage.rb#L16), followed by an EXPIRE on the key.

Redis [no longer recommends using SETNX](https://redis.io/commands/setnx), going so far as to [suggest it may deprecate it at any moment](https://redis.io/commands/set):

> Note: Since the SET command options can replace SETNX, SETEX, PSETEX, it is possible that in future versions of Redis these three commands will be deprecated and finally removed.

Instead, it recommends the [Redlock](https://redis.io/topics/distlock) algorithm, meant to be fault-tolerant by being multi-master. However, I agree with [this analysis of the algorithm](http://martin.kleppmann.com/2016/02/08/how-to-do-distributed-locking.html). The problem of distributed locks is a well-known one, with [Google’s Chubby](https://static.googleusercontent.com/media/research.google.com/en/archive/chubby-osdi06.pdf) being a notable landmark that enabled the search company to build larger and more powerful systems such as Bigtable, which incidentally started the NoSQL movement. The conclusion of that paper is similar to that of Martin Kleppmann: either we are ready to lose data and availability (which happens with single-node Redis, which has the benefit of being sub-millisecond operations) or we really want correctness and fault tolerance, in which case we should use etcd or a database system.

In our case, it can be OK to use a single-node Redis for speed and low latency, and rely on Amazon to move elastic IPs (<2min downtimes upon failover). We can then use a single-Redis-request with a `SET … NX PX`, as suggested [here](https://redis.io/commands/set#patterns) in the Redis documentation, instead of having two round trips to Redis as we currently do. If the SET yields a null reply, it was already locked in the past.

**Comment by dmytro-zakharov** [comment]
fixed in v0.1.2
